#
# Gitlab CI file for SWEET
#

stages:          # List of stages for jobs, and their order of execution
  - test


setup-software-ubuntu18-gcc6:       # This job runs in the build stage, which runs first.
  stage: test
  image: library/ubuntu:18.04
  tags:
    - ci.inria.fr
    - large
  script:
    # Avoid interaction by setting 
    - export DEBIAN_FRONTEND=noninteractive
    # Install packages
    - apt-get update -qq
    - apt-get install -y -qq git make automake cmake python3 wget g++-6 gcc-6 gfortran-6 pkg-config libfreetype6-dev libglu1-mesa-dev
    - export CC=gcc-6
    - export CXX=g++-6
    - export F90=gfortran-6
    - export FC=gfortran-6
    - export LD=ld
    # Setup SWEET

    # Get only head by specifying -- depth 1
    - git clone --depth 1 https://github.com/schreiberx/sweet.git
    - cd sweet
    - source ./activate.sh
    - echo "SWEET environment activated"

    # Compile other required software
    - echo "Fetching and compiling software"
    - cd local_software
    - time ./setup_local_software.sh
    - cd ../

    # Cleaning up things a little bit
    - echo "Cleaning up..."
    - rm -rf .git
    - rm -rf local_software/local_src
    - echo "Finished"

    # We're ready to use SWEET
  
  # Now we just want to store all the software as an artifact to use it for the next steps
  artifacts:
    # Just get everything for the next stage
    untracked: true
    expire_in: 1 day
    name: $CI_JOB_NAME-ubuntu18-gcc6
  

setup-software-ubuntu18-gcc7:       # This job runs in the build stage, which runs first.
  stage: test
  image: library/ubuntu:18.04
  tags:
    - ci.inria.fr
    - large
  script:
    # Avoid interaction by setting 
    - export DEBIAN_FRONTEND=noninteractive
    # Install packages
    - apt-get update -qq
    - apt-get install -y -qq git make automake cmake python3 wget g++-7 gcc-7 gfortran-7 pkg-config libfreetype6-dev libglu1-mesa-dev
    - export CC=gcc-7
    - export CXX=g++-7
    - export F90=gfortran-7
    - export FC=gfortran-7
    - export LD=ld
    # Setup SWEET

    # Get only head by specifying -- depth 1
    - git clone --depth 1 https://github.com/schreiberx/sweet.git
    - cd sweet
    - source ./activate.sh
    - echo "SWEET environment activated"

    # Compile other required software
    - echo "Fetching and compiling software"
    - cd local_software
    - time ./setup_local_software.sh
    - cd ../

    # Cleaning up things a little bit
    - echo "Cleaning up..."
    - rm -rf .git
    - rm -rf local_software/local_src
    - echo "Finished"

    # We're ready to use SWEET
  
  # Now we just want to store all the software as an artifact to use it for the next steps
  artifacts:
    # Just get everything for the next stage
    untracked: true
    expire_in: 1 day
    name: $CI_JOB_NAME-ubuntu18-gcc7
  

setup-software-ubuntu18-gcc8:       # This job runs in the build stage, which runs first.
  stage: test
  image: library/ubuntu:18.04
  tags:
    - ci.inria.fr
    - large
  script:
    # Avoid interaction by setting 
    - export DEBIAN_FRONTEND=noninteractive
    # Install packages
    - apt-get update -qq
    - apt-get install -y -qq git make automake cmake python3 wget g++-8 gcc-8 gfortran-8 pkg-config libfreetype6-dev libglu1-mesa-dev
    - export CC=gcc-8
    - export CXX=g++-8
    - export F90=gfortran-8
    - export FC=gfortran-8
    - export LD=ld
    # Setup SWEET

    # Get only head by specifying -- depth 1
    - git clone --depth 1 https://github.com/schreiberx/sweet.git
    - cd sweet
    - source ./activate.sh
    - echo "SWEET environment activated"

    # Compile other required software
    - echo "Fetching and compiling software"
    - cd local_software
    - time ./setup_local_software.sh
    - cd ../

    # Cleaning up things a little bit
    - echo "Cleaning up..."
    - rm -rf .git
    - rm -rf local_software/local_src
    - echo "Finished"

    # We're ready to use SWEET
  
  # Now we just want to store all the software as an artifact to use it for the next steps
  artifacts:
    # Just get everything for the next stage
    untracked: true
    expire_in: 1 day
    name: $CI_JOB_NAME-ubuntu18-gcc8
  

setup-software-ubuntu20-gcc8:       # This job runs in the build stage, which runs first.
  stage: test
  image: library/ubuntu:20.04
  tags:
    - ci.inria.fr
    - large
  script:
    # Avoid interaction by setting 
    - export DEBIAN_FRONTEND=noninteractive
    # Install packages
    - apt-get update -qq
    - apt-get install -y -qq git make automake cmake python3 wget g++-8 gcc-8 gfortran-8 pkg-config libfreetype-dev libopengl-dev libglu1-mesa-dev libxext-dev
    - export CC=gcc-8
    - export CXX=g++-8
    - export F90=gfortran-8
    - export FC=gfortran-8
    - export LD=ld
    # Setup SWEET

    # Get only head by specifying -- depth 1
    - git clone --depth 1 https://github.com/schreiberx/sweet.git
    - cd sweet
    - source ./activate.sh
    - echo "SWEET environment activated"

    # Compile other required software
    - echo "Fetching and compiling software"
    - cd local_software
    - time ./setup_local_software.sh
    - cd ../

    # Cleaning up things a little bit
    - echo "Cleaning up..."
    - rm -rf .git
    - rm -rf local_software/local_src
    - echo "Finished"

    # We're ready to use SWEET
  
  # Now we just want to store all the software as an artifact to use it for the next steps
  artifacts:
    # Just get everything for the next stage
    untracked: true
    expire_in: 1 day
    name: $CI_JOB_NAME-ubuntu20-gcc8
  

setup-software-ubuntu20-gcc9:       # This job runs in the build stage, which runs first.
  stage: test
  image: library/ubuntu:20.04
  tags:
    - ci.inria.fr
    - large
  script:
    # Avoid interaction by setting 
    - export DEBIAN_FRONTEND=noninteractive
    # Install packages
    - apt-get update -qq
    - apt-get install -y -qq git make automake cmake python3 wget g++-9 gcc-9 gfortran-9 pkg-config libfreetype-dev libopengl-dev libglu1-mesa-dev libxext-dev
    - export CC=gcc-9
    - export CXX=g++-9
    - export F90=gfortran-9
    - export FC=gfortran-9
    - export LD=ld
    # Setup SWEET

    # Get only head by specifying -- depth 1
    - git clone --depth 1 https://github.com/schreiberx/sweet.git
    - cd sweet
    - source ./activate.sh
    - echo "SWEET environment activated"

    # Compile other required software
    - echo "Fetching and compiling software"
    - cd local_software
    - time ./setup_local_software.sh
    - cd ../

    # Cleaning up things a little bit
    - echo "Cleaning up..."
    - rm -rf .git
    - rm -rf local_software/local_src
    - echo "Finished"

    # We're ready to use SWEET
  
  # Now we just want to store all the software as an artifact to use it for the next steps
  artifacts:
    # Just get everything for the next stage
    untracked: true
    expire_in: 1 day
    name: $CI_JOB_NAME-ubuntu20-gcc9
  

setup-software-ubuntu20-gcc10:       # This job runs in the build stage, which runs first.
  stage: test
  image: library/ubuntu:20.04
  tags:
    - ci.inria.fr
    - large
  script:
    # Avoid interaction by setting 
    - export DEBIAN_FRONTEND=noninteractive
    # Install packages
    - apt-get update -qq
    - apt-get install -y -qq git make automake cmake python3 wget g++-10 gcc-10 gfortran-10 pkg-config libfreetype-dev libopengl-dev libglu1-mesa-dev libxext-dev
    - export CC=gcc-10
    - export CXX=g++-10
    - export F90=gfortran-10
    - export FC=gfortran-10
    - export LD=ld
    # Setup SWEET

    # Get only head by specifying -- depth 1
    - git clone --depth 1 https://github.com/schreiberx/sweet.git
    - cd sweet
    - source ./activate.sh
    - echo "SWEET environment activated"

    # Compile other required software
    - echo "Fetching and compiling software"
    - cd local_software
    - time ./setup_local_software.sh
    - cd ../

    # Cleaning up things a little bit
    - echo "Cleaning up..."
    - rm -rf .git
    - rm -rf local_software/local_src
    - echo "Finished"

    # We're ready to use SWEET
  
  # Now we just want to store all the software as an artifact to use it for the next steps
  artifacts:
    # Just get everything for the next stage
    untracked: true
    expire_in: 1 day
    name: $CI_JOB_NAME-ubuntu20-gcc10
  

setup-software-ubuntu22-gcc9:       # This job runs in the build stage, which runs first.
  stage: test
  image: library/ubuntu:22.04
  tags:
    - ci.inria.fr
    - large
  script:
    # Avoid interaction by setting 
    - export DEBIAN_FRONTEND=noninteractive
    # Install packages
    - apt-get update -qq
    - apt-get install -y -qq git make automake cmake python3 wget g++-9 gcc-9 gfortran-9 pkg-config libfreetype-dev libopengl-dev libglu1-mesa-dev libxext-dev
    - export CC=gcc-9
    - export CXX=g++-9
    - export F90=gfortran-9
    - export FC=gfortran-9
    - export LD=ld
    # Setup SWEET

    # Get only head by specifying -- depth 1
    - git clone --depth 1 https://github.com/schreiberx/sweet.git
    - cd sweet
    - source ./activate.sh
    - echo "SWEET environment activated"

    # Compile other required software
    - echo "Fetching and compiling software"
    - cd local_software
    - time ./setup_local_software.sh
    - cd ../

    # Cleaning up things a little bit
    - echo "Cleaning up..."
    - rm -rf .git
    - rm -rf local_software/local_src
    - echo "Finished"

    # We're ready to use SWEET
  
  # Now we just want to store all the software as an artifact to use it for the next steps
  artifacts:
    # Just get everything for the next stage
    untracked: true
    expire_in: 1 day
    name: $CI_JOB_NAME-ubuntu22-gcc9
  

setup-software-ubuntu22-gcc10:       # This job runs in the build stage, which runs first.
  stage: test
  image: library/ubuntu:22.04
  tags:
    - ci.inria.fr
    - large
  script:
    # Avoid interaction by setting 
    - export DEBIAN_FRONTEND=noninteractive
    # Install packages
    - apt-get update -qq
    - apt-get install -y -qq git make automake cmake python3 wget g++-10 gcc-10 gfortran-10 pkg-config libfreetype-dev libopengl-dev libglu1-mesa-dev libxext-dev
    - export CC=gcc-10
    - export CXX=g++-10
    - export F90=gfortran-10
    - export FC=gfortran-10
    - export LD=ld
    # Setup SWEET

    # Get only head by specifying -- depth 1
    - git clone --depth 1 https://github.com/schreiberx/sweet.git
    - cd sweet
    - source ./activate.sh
    - echo "SWEET environment activated"

    # Compile other required software
    - echo "Fetching and compiling software"
    - cd local_software
    - time ./setup_local_software.sh
    - cd ../

    # Cleaning up things a little bit
    - echo "Cleaning up..."
    - rm -rf .git
    - rm -rf local_software/local_src
    - echo "Finished"

    # We're ready to use SWEET
  
  # Now we just want to store all the software as an artifact to use it for the next steps
  artifacts:
    # Just get everything for the next stage
    untracked: true
    expire_in: 1 day
    name: $CI_JOB_NAME-ubuntu22-gcc10
  

setup-software-ubuntu22-gcc11:       # This job runs in the build stage, which runs first.
  stage: test
  image: library/ubuntu:22.04
  tags:
    - ci.inria.fr
    - large
  script:
    # Avoid interaction by setting 
    - export DEBIAN_FRONTEND=noninteractive
    # Install packages
    - apt-get update -qq
    - apt-get install -y -qq git make automake cmake python3 wget g++-11 gcc-11 gfortran-11 pkg-config libfreetype-dev libopengl-dev libglu1-mesa-dev libxext-dev
    - export CC=gcc-11
    - export CXX=g++-11
    - export F90=gfortran-11
    - export FC=gfortran-11
    - export LD=ld
    # Setup SWEET

    # Get only head by specifying -- depth 1
    - git clone --depth 1 https://github.com/schreiberx/sweet.git
    - cd sweet
    - source ./activate.sh
    - echo "SWEET environment activated"

    # Compile other required software
    - echo "Fetching and compiling software"
    - cd local_software
    - time ./setup_local_software.sh
    - cd ../

    # Cleaning up things a little bit
    - echo "Cleaning up..."
    - rm -rf .git
    - rm -rf local_software/local_src
    - echo "Finished"

    # We're ready to use SWEET
  
  # Now we just want to store all the software as an artifact to use it for the next steps
  artifacts:
    # Just get everything for the next stage
    untracked: true
    expire_in: 1 day
    name: $CI_JOB_NAME-ubuntu22-gcc11
  

setup-software-ubuntu22-gcc12:       # This job runs in the build stage, which runs first.
  stage: test
  image: library/ubuntu:22.04
  tags:
    - ci.inria.fr
    - large
  script:
    # Avoid interaction by setting 
    - export DEBIAN_FRONTEND=noninteractive
    # Install packages
    - apt-get update -qq
    - apt-get install -y -qq git make automake cmake python3 wget g++-12 gcc-12 gfortran-12 pkg-config libfreetype-dev libopengl-dev libglu1-mesa-dev libxext-dev
    - export CC=gcc-12
    - export CXX=g++-12
    - export F90=gfortran-12
    - export FC=gfortran-12
    - export LD=ld
    # Setup SWEET

    # Get only head by specifying -- depth 1
    - git clone --depth 1 https://github.com/schreiberx/sweet.git
    - cd sweet
    - source ./activate.sh
    - echo "SWEET environment activated"

    # Compile other required software
    - echo "Fetching and compiling software"
    - cd local_software
    - time ./setup_local_software.sh
    - cd ../

    # Cleaning up things a little bit
    - echo "Cleaning up..."
    - rm -rf .git
    - rm -rf local_software/local_src
    - echo "Finished"

    # We're ready to use SWEET
  
  # Now we just want to store all the software as an artifact to use it for the next steps
  artifacts:
    # Just get everything for the next stage
    untracked: true
    expire_in: 1 day
    name: $CI_JOB_NAME-ubuntu22-gcc12
  
