name: sweet
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - cycler=0.10.0
  - dbus=1.13.18
  - expat=2.4.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - glib=2.68.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.2.0
  - jpeg=9b
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - ncurses=6.2
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openssl=1.1.1k
  - pcre=8.45
  - pillow=8.2.0
  - pip=21.1.3
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.9.5
  - python-dateutil=2.8.1
  - qt=5.9.7
  - readline=8.1
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - tornado=6.1
  - tzdata=2021a
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
